org.gradle.jvmargs=-Xmx2048M
android.useAndroidX=true
android.enableJetifier=true

 
android.enableR8.fullMode=false
android.native.pageSize=16384
android.bundle.enablePageSizeAgnosticNativeLibs=true
android.enableNativeLibraryPageAlignment=true

 
org.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk-17.jdk/Contents/Home